Repository Digital-Voting-Team/Digital-Voting, pull requests merged in 2023-06, with the labels that each got.

#33 Feature/connections
  cmd/main/main.go
  pkg/blockchain/block/block.go
  pkg/blockchain/block/witness.go
  pkg/validator/communication.go
  pkg/validator/connections/web_socket/network_node/network_node.go
  pkg/validator/repository/indexed_data.go
  pkg/validator/repository/indexed_groups/group_dto.go
  pkg/validator/repository/indexed_votings/voting_dto.go
  pkg/validator/validator.go
  pkg/validator/validator_test.go
Labels: enhancement, new feature, back end, fix

#32 Implemented EdDSA algorithm
  pkg/signature/curve/curve.go
  pkg/signature/curve/montgomery_curve.go
  pkg/signature/keys/from_address.go
  pkg/signature/keys/key_pair.go
  pkg/signature/keys/kp_interface.go
  pkg/signature/signatures/ring_signature/ring_signature.go
  pkg/signature/signatures/single_signature/single_signature.go
  pkg/signature/signatures/single_signature/single_signature_test.go
  pkg/signature/strkey/main.go
Labels: enhancement, new feature, back end

#34 Replaced usage of ECDSA to EdDSA
  pkg/blockchain/block/witness.go
  pkg/blockchain/transaction/transaction.go
  pkg/signature/signatures/single_signature/single_signature.go
  pkg/signer/block_signer.go
  pkg/signer/transaction_signer.go
  pkg/validator/connections/web_socket/network_node/network_node.go
Labels: enhancement, new feature, back end

#36 Develop
  cmd/main/main.go
  go.mod
  go.sum
  pkg/blockchain/block/block.go
  pkg/blockchain/block/block_test.go
  pkg/blockchain/block/body.go
  pkg/blockchain/block/header.go
  pkg/blockchain/block/merkle_tree/merkle_tree.go
  pkg/blockchain/block/merkle_tree/merkle_tree_test.go
  pkg/blockchain/block/merkle_tree/transactions_merkle_tree.go
  pkg/blockchain/block/merkle_tree/transactions_merkle_tree_test.go
  pkg/blockchain/block/witness.go
  pkg/blockchain/blockchain.go
  pkg/blockchain/blockchain_test.go
  pkg/blockchain/transaction/transaction.go
  pkg/blockchain/transaction/transaction_body.go
  pkg/blockchain/transaction/transaction_interface.go
  pkg/blockchain/transaction/transaction_json/tx_json.go
  pkg/blockchain/transaction/transaction_json/tx_json_test.go
  pkg/blockchain/transaction/transaction_specific/tx_account_creation.go
  pkg/blockchain/transaction/transaction_specific/tx_group_creation.go
  pkg/blockchain/transaction/transaction_specific/tx_vote.go
  pkg/blockchain/transaction/transaction_specific/tx_vote_anonymus.go
  pkg/blockchain/transaction/transaction_specific/tx_voting_creation.go
  pkg/models/account/account.go
  pkg/signature/curve/curve.go
  pkg/signature/curve/montgomery_curve.go
  pkg/signature/curve/point.go
  pkg/signature/keys/key_pair.go
  pkg/signature/keys/key_pair_test.go
  pkg/signature/keys/kp_interface.go
  pkg/signature/signatures/ring_signature/ring_signature.go
  pkg/signature/signatures/ring_signature/ring_signature_test.go
  pkg/signature/signatures/single_signature/single_signature.go
  pkg/signature/signatures/single_signature/single_signature_test.go
  pkg/signature/signatures/utils/math_utils.go
  pkg/signature/strkey/main.go
  pkg/signer/block_signer.go
  pkg/signer/transaction_signer.go
  pkg/validator/communication.go
  pkg/validator/connections/web_socket/network_node/network_node.go
  pkg/validator/connections/web_socket/user_api/user_api.go
  pkg/validator/mem_pool.go
  pkg/validator/repository/account_manager/account_manager.go
  pkg/validator/repository/indexed_data.go
  pkg/validator/repository/indexed_groups/group_dto.go
  pkg/validator/repository/indexed_groups/groups.go
  pkg/validator/repository/indexed_groups/groups_test.go
  pkg/validator/repository/indexed_votings/voting_dto.go
  pkg/validator/repository/indexed_votings/votings.go
  pkg/validator/repository/indexed_votings/votings_test.go
  pkg/validator/validation/transaction_validation.go
  pkg/validator/validation/transaction_validation_test.go
  pkg/validator/validator.go
  pkg/validator/validator_test.go
Labels: new feature, back end
